### PR TITLE
Enable Report to have Multiple Languages

### PR DESCRIPTION
**Pull request by blueworrybear**

### CODE REVIEW

**Comment by blueworrybear** [comment]
treemap

### Coverage: 39.5%

||File|Coverage|
|--|--|--------|
||routers/web/web.go|0.00|
||models/user.go|0.78|
||routers/api/report/badge.go|0.00|
||routers/api/repo/context.go|0.69|
||routers/web/logout.go|0.00|
||service/perl/report.go|0.66|
|:arrow_up_small:|models/models.go|0.58|
||modules/scm/user.go|0.00|
||routers/api/repo/repo.go|0.14|
||routers/web/login.go|0.00|
||models/error.go|0.57|
||modules/scm/pr.go|0.20|
||service/perl/coverage.go|0.76|
|:arrow_down_small:|modules/report/report.go|0.64|
||modules/scm/git.go|0.00|
||modules/charts/chart.go|0.00|
||service/coverage/coverage.go|0.33|
||modules/scm/content.go|0.48|
||modules/scm/hook.go|0.00|
||modules/scm/repo.go|0.60|
||modules/scm/scm.go|0.18|
||routers/web/static.go|0.00|
||config/config.go|0.44|
|:arrow_up_small:|models/report.go|0.84|
||modules/git/git.go|0.57|
||modules/git/repo.go|0.44|
|:arrow_up_small:|routers/api/report/report.go|0.40|
||routers/web/context.go|0.00|
||service/golang/report.go|0.66|
||service/perl/file.go|0.87|
|:arrow_up_small:|modules/charts/treemap.go|0.94|
||models/repo.go|0.80|
||routers/api/repo/hook.go|0.35|
||modules/scm/client.go|0.00|
||modules/git/commit.go|0.89|

**Comment by blueworrybear** [comment]
treemap

### Coverage: 39.6%

||File|Coverage|
|--|--|--------|
||routers/api/report/badge.go|0.00|
||service/perl/coverage.go|0.76|
||models/user.go|0.78|
||modules/scm/hook.go|0.00|
||modules/scm/user.go|0.00|
||modules/scm/git.go|0.00|
||routers/api/repo/hook.go|0.35|
||models/repo.go|0.80|
||routers/web/login.go|0.00|
||routers/web/logout.go|0.00|
||service/golang/report.go|0.66|
||models/error.go|0.57|
|:arrow_up_small:|models/models.go|0.58|
|:arrow_down_small:|modules/report/report.go|0.64|
||routers/api/repo/context.go|0.69|
|:arrow_up_small:|routers/api/report/report.go|0.39|
||routers/web/context.go|0.00|
||modules/charts/chart.go|0.00|
||modules/scm/pr.go|0.20|
||modules/scm/scm.go|0.18|
||modules/git/commit.go|0.89|
||routers/web/web.go|0.00|
||routers/web/static.go|0.00|
||service/perl/report.go|0.66|
||modules/git/repo.go|0.44|
||service/coverage/coverage.go|0.33|
||config/config.go|0.44|
|:arrow_up_small:|modules/charts/treemap.go|0.98|
|:arrow_up_small:|models/report.go|0.83|
||routers/api/repo/repo.go|0.14|
||modules/git/git.go|0.57|
||modules/scm/content.go|0.48|
||modules/scm/repo.go|0.60|
||modules/scm/client.go|0.00|
|:arrow_up_small:|service/perl/file.go|0.90|

**Comment by blueworrybear** [comment]
treemap

### Coverage: 39.6%

||File|Coverage|
|--|--|--------|
||models/user.go|0.78|
||modules/scm/content.go|0.48|
||modules/scm/repo.go|0.60|
||routers/api/repo/context.go|0.69|
||routers/api/report/badge.go|0.00|
|:arrow_up_small:|routers/api/report/report.go|0.39|
||service/golang/report.go|0.66|
|:arrow_down_small:|modules/report/report.go|0.64|
||routers/api/repo/repo.go|0.14|
||service/coverage/coverage.go|0.33|
||modules/charts/chart.go|0.00|
||modules/scm/client.go|0.00|
||modules/scm/git.go|0.00|
||modules/scm/hook.go|0.00|
||modules/git/repo.go|0.44|
||routers/web/static.go|0.00|
||service/perl/coverage.go|0.76|
|:arrow_up_small:|modules/charts/treemap.go|0.98|
||models/repo.go|0.80|
||modules/scm/scm.go|0.18|
||modules/git/commit.go|0.89|
||routers/web/login.go|0.00|
|:arrow_up_small:|service/perl/file.go|0.90|
||modules/scm/user.go|0.00|
||modules/scm/pr.go|0.20|
||routers/web/context.go|0.00|
||routers/web/logout.go|0.00|
||modules/git/git.go|0.57|
||models/error.go|0.57|
|:arrow_up_small:|models/models.go|0.58|
|:arrow_up_small:|models/report.go|0.83|
||config/config.go|0.44|
||routers/api/repo/hook.go|0.35|
||routers/web/web.go|0.00|
||service/perl/report.go|0.66|

**Comment by blueworrybear** [comment]
treemap

### [Coverage: 0.0%](https://covergates.com/report/github/covergates/covergates?ref=bdfcba2c247bcf6a7c84d3264dc5797b7ee32bf7)

||File|Coverage|
|--|--|--------|

**Comment by luwol03** [comment]
hello @blueworrybear, you're back? or is that a bug?

**Pull request merged**
