### PR TITLE
Bitbucket!

### LINKED ISSUE #23: Bitbucket support
Hello!

I'd like to help to build support for bitbucket but I need a bit of help with it :)

I can see you recently added support for [GitLab](https://github.com/covergates/covergates/pull/21/files) what's cool and I'll base my work on it.

### PR DESCRIPTION
**Pull request by bkielbasa**
Fixes #23

### CODE REVIEW

**Comment by blueworrybear** [comment]
treemap

### [Coverage: 60.7%](https://covergates.com/report/github/covergates/covergates?ref=5c85893d883e5c9d018031bc51991602f4cc6017)

||File|Coverage|
|--|--|--------|
||web/src/server.ts|0.53|
||web/src/vue.ts|1.00|
||web/src/components/AccountButton.vue|0.81|
||web/src/components/CommitButton.vue|0.25|
|:arrow_down_small:|web/src/components/RepoListItem.vue|0.93|
||web/src/components/ReportEmpty.vue|0.67|
||web/src/components/ReportGuide.vue|0.30|
||web/src/components/ReportOverview.vue|0.81|
||web/src/mixins/report.ts|0.55|
||web/src/plugins/http.ts|0.70|
||web/src/store/index.ts|0.93|
||web/src/store/modules/report/actions.ts|0.62|
||web/src/store/modules/report/index.ts|1.00|
||web/src/store/modules/report/mutations.ts|0.14|
||web/src/store/modules/repository/actions.ts|0.41|
||web/src/store/modules/repository/index.ts|1.00|
||web/src/store/modules/repository/mutations.ts|0.00|
||web/src/store/modules/user/actions.ts|0.36|
||web/src/store/modules/user/index.ts|1.00|
||web/src/store/modules/user/mutations.ts|0.12|

**Comment by blueworrybear** [comment]
treemap

### [Coverage: 47.4%](https://covergates.com/report/github/covergates/covergates?ref=9f0745caa5d130a1ee5fa31f76bfd8f92fb9e386)

||File|Coverage|
|--|--|--------|
||service/perl/coverage.go|0.76|
|:arrow_down_small:|config/config.go|0.38|
||modules/charts/chart.go|0.00|
||modules/git/repo.go|0.47|
||models/oauth.go|0.79|
||modules/scm/git.go|0.06|
||modules/scm/repo.go|0.55|
||routers/api/user/repo.go|1.00|
||service/python/report.go|0.84|
||cmd/cli/main.go|0.00|
||modules/git/git.go|0.83|
||models/models.go|0.59|
||modules/oauth/store.go|0.53|
||routers/web/login.go|0.00|
||modules/charts/treemap.go|0.94|
||modules/git/commit.go|0.89|
||models/report.go|0.83|
||modules/oauth/oauth.go|0.84|
||modules/scm/content.go|0.48|
||service/golang/report.go|0.82|
||service/ruby/report.go|0.70|
||routers/web/static.go|0.00|
|:arrow_down_small:|models/user.go|0.71|
||routers/api/repo/hook.go|0.35|
||routers/api/repo/repo.go|0.17|
|:arrow_down_small:|modules/scm/scm.go|0.12|
||modules/scm/user.go|0.00|
||routers/web/context.go|0.00|
||routers/web/logout.go|0.00|
||service/lcov/report.go|0.72|
||modules/charts/card.go|0.97|
||routers/api/repo/context.go|0.69|
||modules/scm/client.go|0.00|
||routers/api/report/middleware.go|0.24|
||service/clover/report.go|0.76|
||service/perl/file.go|0.90|
||models/error.go|0.57|
||modules/scm/pr.go|0.20|
||service/perl/report.go|0.66|
||routers/api/report/context.go|0.50|
||routers/api/report/badge.go|0.00|
||service/coverage/coverage.go|0.25|
||routers/web/web.go|0.00|
||models/repo.go|0.83|
||modules/repo/service.go|0.75|
||modules/report/report.go|0.68|
||modules/scm/hook.go|0.00|
||routers/api/user/user.go|0.00|
||routers/api/user/oauth.go|0.89|
||routers/api/report/report.go|0.45|

**Comment by blueworrybear** [comment]
treemap

### [Coverage: 54.0%](https://covergates.com/report/github/covergates/covergates?ref=9f0745caa5d130a1ee5fa31f76bfd8f92fb9e386)

||File|Coverage|
|--|--|--------|
||service/perl/coverage.go|0.76|
|:arrow_down_small:|config/config.go|0.38|
||modules/charts/chart.go|0.00|
||modules/git/repo.go|0.47|
||models/oauth.go|0.79|
||modules/scm/git.go|0.06|
||modules/scm/repo.go|0.55|
||routers/api/user/repo.go|1.00|
||service/python/report.go|0.84|
||cmd/cli/main.go|0.00|
||modules/git/git.go|0.83|
||models/models.go|0.59|
||modules/oauth/store.go|0.53|
||routers/web/login.go|0.00|
||modules/charts/treemap.go|0.94|
||modules/git/commit.go|0.89|
||models/report.go|0.83|
||modules/oauth/oauth.go|0.84|
||modules/scm/content.go|0.48|
||service/golang/report.go|0.82|
||service/ruby/report.go|0.70|
||routers/web/static.go|0.00|
|:arrow_down_small:|models/user.go|0.71|
||routers/api/repo/hook.go|0.35|
||routers/api/repo/repo.go|0.17|
|:arrow_down_small:|modules/scm/scm.go|0.12|
||modules/scm/user.go|0.00|
||routers/web/context.go|0.00|
||routers/web/logout.go|0.00|
||service/lcov/report.go|0.72|
||modules/charts/card.go|0.97|
||routers/api/repo/context.go|0.69|
||modules/scm/client.go|0.00|
||routers/api/report/middleware.go|0.24|
||service/clover/report.go|0.76|
||service/perl/file.go|0.90|
||models/error.go|0.57|
||modules/scm/pr.go|0.20|
||service/perl/report.go|0.66|
||routers/api/report/context.go|0.50|
||routers/api/report/badge.go|0.00|
||service/coverage/coverage.go|0.25|
||routers/web/web.go|0.00|
||models/repo.go|0.83|
||modules/repo/service.go|0.75|
||modules/report/report.go|0.68|
||modules/scm/hook.go|0.00|
||routers/api/user/user.go|0.00|
||routers/api/user/oauth.go|0.89|
||routers/api/report/report.go|0.45|
||web/src/server.ts|0.53|
||web/src/vue.ts|1.00|
||web/src/components/AccountButton.vue|0.81|
||web/src/components/CommitButton.vue|0.25|
|:arrow_down_small:|web/src/components/RepoListItem.vue|0.93|
||web/src/components/ReportEmpty.vue|0.67|
||web/src/components/ReportGuide.vue|0.30|
||web/src/components/ReportOverview.vue|0.81|
||web/src/mixins/report.ts|0.55|
||web/src/plugins/http.ts|0.70|
||web/src/store/index.ts|0.93|
||web/src/store/modules/report/actions.ts|0.62|
||web/src/store/modules/report/index.ts|1.00|
||web/src/store/modules/report/mutations.ts|0.14|
||web/src/store/modules/repository/actions.ts|0.41|
||web/src/store/modules/repository/index.ts|1.00|
||web/src/store/modules/repository/mutations.ts|0.00|
||web/src/store/modules/user/actions.ts|0.36|
||web/src/store/modules/user/index.ts|1.00|
||web/src/store/modules/user/mutations.ts|0.12|

**Comment by bkielbasa** [comment]
I created this PR 1 year ago. No feedback so closing!

**Pull request closed without merging**
